server:
  port: 8090

# Set here configurations for the database connection
spring:
  datasource:
    url: jdbc:mariadb://localhost:3308/tiendabd
    username: root
    password: sqlMD3
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        format_sql: true

# LOGGING LEVEL
logging:
  level:
    root: INFO

# JWT
jwt:
  secret: BeVH-wD7F3iNxpn2hrR5ZYxVaYf8G1ecfQrt41zj3DgxYKlKtrp4JomeHjckMb-vLWizROrRQ5k7zUeqNJXDvg
  expirationDateInMs: 3600
  refreshExpirationDateInMs: 900
